spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8800
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
